[package]
name = "matrix-cli"
version = "0.1.0"
authors = ["Robin Neal <robinneal429@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
matrix-api = { path = '../matrix-api'}